build:
    nodes:
        analysis:
            environment:
                php:
                    version: 7.4
            tests:
                override:
                    - php-scrutinizer-run

filter:
    excluded_paths:
        - 'Tests/*'
        - 'Migration/*'
        - 'Documentation/*'
    paths:
        - 'Classes/*'
        - 'template/*'
        - '*'

tools:
    external_code_coverage:
        timeout: 750
        runs: 2
    php_cpd:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: TYPO3CMS
    php_cs_fixer:
        enabled: true
    php_hhvm:
        enabled: true
        config:
            use_undeclared_constant:  false
    php_mess_detector:
        enabled: true
        config:
            controversial_rules:
                superglobals: false
    php_pdepend:
        enabled: true
    php_analyzer:
        enabled: true
    sensiolabs_security_checker: true
