<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2009-12-21 14:12

$extensionPath = t3lib_extMgm::extPath('crawler');
return array(
	'tx_crawler_api' => $extensionPath . 'class.tx_crawler_api.php',
	'tx_crawler_auth' => $extensionPath . 'class.tx_crawler_auth.php',
	'tx_crawler_contextmenu' => $extensionPath . 'class.tx_crawler_contextMenu.php',
	'tx_crawler_lib' => $extensionPath . 'class.tx_crawler_lib.php',
	'tx_crawler_tcafunc' => $extensionPath . 'class.tx_crawler_tcaFunc.php',
	'tx_crawler_cli_flush' => $extensionPath . 'cli/class.tx_crawler_cli_flush.php',
	'tx_crawler_cli' => $extensionPath . 'cli/class.tx_crawler_cli.php',
	'tx_crawler_cli_im' => $extensionPath . 'cli/class.tx_crawler_cli_im.php',
	'tx_crawler_domain_events_dispatcher' => $extensionPath . 'domain/events/class.tx_crawler_domain_events_dispatcher.php',
	'tx_crawler_domain_events_observer' => $extensionPath . 'domain/events/interface.tx_crawler_domain_events_observer.php',
	'tx_crawler_domain_lib_abstract_dbobject' => $extensionPath . 'domain/lib/class.tx_crawler_domain_lib_abstract_dbobject.php',
	'tx_crawler_domain_lib_abstract_repository' => $extensionPath . 'domain/lib/class.tx_crawler_domain_lib_abstract_repository.php',
	'tx_crawler_domain_process_manager' => $extensionPath . 'domain/process/class.tx_crawler_domain_process_manager.php',
	'tx_crawler_domain_process' => $extensionPath . 'domain/process/class.tx_crawler_domain_process.php',
	'tx_crawler_domain_process_collection' => $extensionPath . 'domain/process/class.tx_crawler_domain_process_collection.php',
	'tx_crawler_domain_process_repository' => $extensionPath . 'domain/process/class.tx_crawler_domain_process_repository.php',
	'tx_crawler_domain_queue_entry' => $extensionPath . 'domain/queue/class.tx_crawler_domain_queue_entry.php',
	'tx_crawler_domain_queue_repository' => $extensionPath . 'domain/queue/class.tx_crawler_domain_queue_repository.php',
	'tx_crawler_domain_reason' => $extensionPath . 'domain/reason/class.tx_crawler_domain_reason.php',
	'tx_crawler_hooks_tsfe' => $extensionPath . 'hooks/class.tx_crawler_hooks_tsfe.php',
	'tx_crawler_modfunc1' => $extensionPath . 'modfunc1/class.tx_crawler_modfunc1.php',
	'tx_crawler_scheduler_im' => $extensionPath . 'scheduler/class.tx_crawler_scheduler_im.php',
	'tx_crawler_scheduler_imadditionalfieldprovider' => $extensionPath . 'scheduler/class.tx_crawler_scheduler_imAdditionalFieldProvider.php',
	'tx_crawler_scheduler_crawl' => $extensionPath . 'scheduler/class.tx_crawler_scheduler_crawl.php',
	'tx_crawler_scheduler_crawladditionalfieldprovider' => $extensionPath . 'scheduler/class.tx_crawler_scheduler_crawlAdditionalFieldProvider.php',
	'tx_crawler_scheduler_crawlmultiprocess' => $extensionPath . 'scheduler/class.tx_crawler_scheduler_crawlMultiProcess.php',
	'tx_crawler_scheduler_crawlmultiprocessadditionalfieldprovider' => $extensionPath . 'scheduler/class.tx_crawler_scheduler_crawlMultiProcessAdditionalFieldProvider.php',
	'tx_crawler_scheduler_flush' => $extensionPath . 'scheduler/class.tx_crawler_scheduler_flush.php',
	'tx_crawler_scheduler_flushadditionalfieldprovider' => $extensionPath . 'scheduler/class.tx_crawler_scheduler_flushAdditionalFieldProvider.php',
	'tx_crawler_system_validator' => $extensionPath . 'system/class.tx_crawler_system_validator.php',
	'tx_crawler_api_testcase' => $extensionPath . 'tests/class.tx_crawler_api_testcase.php',
	'tx_crawler_domain_events_dispatcher_testcase' => $extensionPath . 'tests/events/class.tx_crawler_domain_events_dispatcher_testcase.php',
	'tx_crawler_domain_events_test' => $extensionPath . 'tests/events/data/class.tx_crawler_domain_events_test.php',
	'tx_crawler_view_pagination' => $extensionPath . 'view/class.tx_crawler_view_pagination.php',
	'tx_crawler_view_process_list' => $extensionPath . 'view/process/class.tx_crawler_view_process_list.php',
);
?>
