name: Feature Request
description: Create a feature request
title: [FEATURE] <title>
labels: [feature]
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is. Ex. I have an issue when [...]
    validations:
      required: false
  - type: textarea
      attributes:
        label: Describe the solution you would like
        description: A clear and concise description of what you want to happen. Add any considered drawbacks.
      validations:
        required: false
  - type: textarea
      attributes:
        label: Describe alternatives you've considered
        description: A clear and concise description of any alternative solutions or features you've considered.
      validations:
        required: false
  - type: textarea
      attributes:
        label: Teachability, Documentation, Adoption, Migration Strategy
        description: If you can, explain how users will be able to use this and possibly amend the documentation
      validations:
        required: false
