name: Automatic Approve
on:
  schedule:
    - cron:  "*/15 * * * *"
jobs:
  automatic-approve:
    name: Automatic Approve
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Approve
        uses: mheap/automatic-approve-action@v1
        with:
          token: ${{ secrets.CRAWLER_GITHUB_TOKEN }}
          workflows: "Acceptance.yml,AutomaticApproval.yml,BackwardCompatibilityCheck.yml,Coveralls.yml,DBMS.yml,Deploy.yml,Greetings.yml,MutationTests.yml,Requirement.yml,SonarCloud.yml,StaticAnalysis.yaml,Tests.yml"
